### ISSUE TITLE
'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008

### ISSUE THREAD

**Issue by scottyeung** [bauer-jan/stock-analysis-with-llm#2]
`Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than o
r equal to 3008 (Service: Lambda, Status Code: 400, Request ID: 22462c72-a924-4eb4-bf85-e01b6c63002b)" (RequestToken: 0
eaf9139-0512-c83f-4c88-cc113fda883e, HandlerErrorCode: InvalidRequest)`

Is there anything you can suggest to make it work? Thank you for making this happen

**Comment by bauer-jan** [comment]
Did you change the memory allocation to the AWS Lambda function in the CDK [construct](https://github.com/bauer-jan/stock-analysis-with-llm/blob/e2c0867d918084ca978771ec51ef1ca41dd506e1/infrastructure/lib/infrastructure-stack.ts#L87C1-L87C30)? It is currently set to             memorySize: 4048 which should be enough. Does your region where you deploy the stack supports the memory size for AWS Lambda?

**Comment by bauer-jan** [comment]
You can also try to run the stack with a lower AWS Lambda memory size value, just change it to 3008.

**Comment by scottyeung** [comment]
> Did you change the memory allocation to the AWS Lambda function in the CDK [construct](https://github.com/bauer-jan/stock-analysis-with-llm/blob/e2c0867d918084ca978771ec51ef1ca41dd506e1/infrastructure/lib/infrastructure-stack.ts#L87C1-L87C30)? It is currently set to memorySize: 4048 which should be enough. Does your region where you deploy the stack supports the memory size for AWS Lambda?

My region currently supports 3008 or less, that's what I found in Basic Configuration when I set to 4048
`'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008`

**Comment by scottyeung** [comment]
Thank you so much for helping!

**Comment by bauer-jan** [comment]
No worries, just be careful when you run it. AWS Bedrock can become quite expensive fast
